name: Grgac - Pokretanje integracijskih testova
on:
  push:
    branches: [master]
    paths:
      - 'Software/Padeler/**'
      - '.github/workflows/grgac-integrationTests.yml'
  pull_request:
    branches: [master]
    paths:
      - 'Software/Padeler/**'
      - '.github/workflows/grgac-integrationTests.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: Software/Padeler

    steps:
      - name: Dohvat izvornog koda
        uses: actions/checkout@v4

      - name: Postavljanje MSBuild alata
        uses: microsoft/setup-msbuild@v2

      - name: Postavljanje NuGet alata
        uses: NuGet/setup-nuget@v2

      - name: Postavljanje VSTest alata
        uses: darenm/Setup-VSTest@v1.3

      - name: Restore NuGet paketa
        run: nuget restore Padeler.sln

      - name: Build rješenja
        run: msbuild.exe Padeler.sln /p:platform="Any CPU" /p:configuration="Release"

      - name: Pokretanje integracijskih testova
        run: vstest.console.exe .\IntegrationTests\bin\Release\net48\IntegrationTests.dll /Logger:trx /ResultsDirectory:TestResults

      - name: Spremanje rezultata testova
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grgac-integrationTests-results
          path: Software/Padeler/TestResults/*.trx
